/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_api: () => import("@/views/manage/api/index.vue"),
  manage_codegen: () => import("@/views/manage/codegen/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_radar_exceptions: () => import("@/views/manage/radar/exceptions/index.vue"),
  manage_radar_monitor: () => import("@/views/manage/radar/monitor/index.vue"),
  manage_radar_overview: () => import("@/views/manage/radar/overview/index.vue"),
  manage_radar_queries: () => import("@/views/manage/radar/queries/index.vue"),
  manage_radar_requests: () => import("@/views/manage/radar/requests/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
};
