/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 1,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_api',
        path: '/manage/api',
        component: 'view.manage_api',
        meta: {
          title: 'manage_api',
          i18nKey: 'route.manage_api',
          icon: 'ant-design:api-outlined',
          order: 1
        }
      },
      {
        name: 'manage_codegen',
        path: '/manage/codegen',
        component: 'view.manage_codegen',
        meta: {
          title: 'manage_codegen',
          i18nKey: 'route.manage_codegen',
          icon: 'mdi:code-json',
          order: 5,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 4,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_radar',
        path: '/manage/radar',
        meta: {
          title: 'manage_radar',
          i18nKey: 'route.manage_radar',
          icon: 'mdi:radar',
          order: 7
        },
        children: [
          {
            name: 'manage_radar_exceptions',
            path: '/manage/radar/exceptions',
            component: 'view.manage_radar_exceptions',
            meta: {
              title: 'manage_radar_exceptions',
              i18nKey: 'route.manage_radar_exceptions',
              icon: 'mdi:bug-outline',
              order: 4
            }
          },
          {
            name: 'manage_radar_monitor',
            path: '/manage/radar/monitor',
            component: 'view.manage_radar_monitor',
            meta: {
              title: 'manage_radar_monitor',
              i18nKey: 'route.manage_radar_monitor',
              icon: 'mdi:monitor-dashboard',
              order: 5
            }
          },
          {
            name: 'manage_radar_overview',
            path: '/manage/radar/overview',
            component: 'view.manage_radar_overview',
            meta: {
              title: 'manage_radar_overview',
              i18nKey: 'route.manage_radar_overview',
              icon: 'mdi:chart-box-outline',
              order: 1
            }
          },
          {
            name: 'manage_radar_queries',
            path: '/manage/radar/queries',
            component: 'view.manage_radar_queries',
            meta: {
              title: 'manage_radar_queries',
              i18nKey: 'route.manage_radar_queries',
              icon: 'mdi:database-search',
              order: 3
            }
          },
          {
            name: 'manage_radar_requests',
            path: '/manage/radar/requests',
            component: 'view.manage_radar_requests',
            meta: {
              title: 'manage_radar_requests',
              i18nKey: 'route.manage_radar_requests',
              icon: 'mdi:swap-horizontal',
              order: 2
            }
          }
        ]
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 3,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 2,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
